BM, CBS, aepc, pri & DHM
Know-Nepal/government-websites pull request #20
Opened 2023-04-05 09:48 UTC by Rezy-Dev

2023-04-05 09:56 UTC, ankurgajurel approved these changes
naice .. thanks for your contribution

2023-04-05 10:02 UTC, ankurgajurel approved these changes
howboutnow

2023-04-05 10:07 UTC, ankurgajurel approved these changes

2023-04-05 12:42 UTC, thenishantsapkota requested changes

2023-04-05 12:42 UTC, thenishantsapkota commented on data/websites.json
> +        "name": "President Office",
How about keeping the official name of the office?

2023-04-05 12:42 UTC, thenishantsapkota commented on data/websites.json
> +        "name": "Policy Research Institute",
Same here
```suggest
"name": "Office of the Policy Research Institute"
```

2023-04-05 16:22 UTC, thenishantsapkota requested changes

2023-04-05 16:22 UTC, thenishantsapkota commented on data/websites.json
> +        "description": "Official Website Of the Office of the Policy Research Institute"
```suggestion
        "description": "Official Website of the Office of the Policy Research Institute"
```

2023-04-05 16:22 UTC, thenishantsapkota commented on data/websites.json
> +        "description": "Official Website Of the Office of the President of Nepal"
```suggestion
        "description": "Official Website of the Office of the President of Nepal"
```

2023-04-06 03:12 UTC, thenishantsapkota approved these changes

2023-04-06 03:12 UTC, thenishantsapkota commented
Thank you for your contribution @Rezy-Dev 🥳

2023-04-06 03:12 UTC, merged