District Offices Syangja
Know-Nepal/government-websites pull request #45
Opened 2023-10-03 15:56 UTC by ori-on1

2023-10-03 16:09 UTC, TheLearneer requested changes

2023-10-03 16:09 UTC, TheLearneer commented on data/websites.json
> +
Please remove this empty line

2023-10-03 16:09 UTC, TheLearneer commented on data/websites.json
> +      {
Please properly format the file using prettier 🙏

2023-10-04 11:17 UTC, thenishantsapkota approved these changes

2023-10-04 11:18 UTC, thenishantsapkota commented
Please resolve all the merge conflicts!
Thank you

2023-10-04 13:00 UTC, closed without merging