Ruru/resunga
Know-Nepal/government-websites pull request #46
Opened 2023-10-03 16:00 UTC by shree404

2023-10-03 16:05 UTC, TheLearneer requested changes
Please remove the duplicate

2023-10-03 16:05 UTC, TheLearneer commented on data/websites.json
> +      "name": "Rainadevi Chhahara Rural Municipality",
This site already exists!

2023-10-04 13:28 UTC, TheLearneer approved these changes
LGTM

2023-10-04 16:12 UTC, thenishantsapkota requested changes
Please resolve the merge conflicts again.
Thank you

2023-10-06 08:04 UTC, closed without merging