Nepal Oil Corporation Added
Know-Nepal/government-websites pull request #56
Opened 2023-10-06 14:52 UTC by ori-on1

2023-10-06 15:18 UTC, sudipsigdel requested changes

2023-10-06 15:18 UTC, sudipsigdel commented on data/websites.json
> +      "name": "Nepal Oil COrporation",
"name": "Nepal Oil Corporation",

2023-10-06 16:01 UTC, sudipsigdel approved these changes

2023-10-06 16:12 UTC, sudipsigdel requested changes
As mentioned by @TheLearneer, complete that and you are good to go.

2023-10-07 14:41 UTC, TheLearneer commented
Hi @ori-on1 👋 
Your base branch contains other commit which you had made for other PRs.

Please always switch back to develop branch before creating a new branch.
For now I am closing this PR, because it contains merge conflict because it has commits from previous PRs.

2023-10-07 14:41 UTC, closed without merging