Some Gov. Websites Banke
Know-Nepal/government-websites pull request #69
Opened 2023-10-09 17:44 UTC by iam-neo

2023-10-13 03:03 UTC, thenishantsapkota requested changes
The changes are not in alphabetical order. Can you order them in alphabetical order?

2023-10-13 11:00 UTC, iam-neo reviewed
Arranged in alphabetical order. 
please check once

2023-10-13 11:10 UTC, thenishantsapkota requested changes

2023-10-13 11:10 UTC, thenishantsapkota commented on data/websites.json
> +      "name": "Nepalgunj sub metropolitan",
```suggestion
      "name": "Nepalgunj Sub Metropolitan"
```

2023-10-13 11:10 UTC, thenishantsapkota commented on data/websites.json
> +
Why is there a random space here?

2023-10-13 11:10 UTC, thenishantsapkota commented on data/websites.json
> +      "url": "https://daobanke.moha.gov.np/en",
Remove the `/en` at the end of the website here!

2023-10-14 02:14 UTC, iam-neo reviewed
Done!

2023-10-14 02:26 UTC, thenishantsapkota requested changes

2023-10-14 02:26 UTC, thenishantsapkota commented on data/websites.json
> +}
There's still no new line at the end of the file.
Please format the files using prettier and push the commit again.

2023-10-14 03:07 UTC, iam-neo reviewed
File updated, please check at once

2023-10-14 03:49 UTC, thenishantsapkota approved these changes
LGTM!

2023-10-14 03:50 UTC, thenishantsapkota commented
Thank you for your contribution @iam-neo!

2023-10-14 03:50 UTC, merged